"""empty message

Revision ID: 052f5f4240ca
Revises: 46f7ee9484f0
Create Date: 2024-12-28 21:11:13.748060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052f5f4240ca'
down_revision = '46f7ee9484f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('cv_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cover_letter_filename', sa.String(length=100), nullable=True))
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.drop_column('cv_file')
        batch_op.drop_column('phone')
        batch_op.drop_column('cover_letter_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aggregator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_letter_file', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cv_file', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('cover_letter_filename')
        batch_op.drop_column('cv_filename')
        batch_op.drop_column('full_phone')

    # ### end Alembic commands ###
