"""empty message

Revision ID: 46f7ee9484f0
Revises: 
Create Date: 2024-12-28 18:36:18.598619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46f7ee9484f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('lga', sa.String(length=100), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.Column('cv_file', sa.String(length=200), nullable=False),
    sa.Column('cover_letter_file', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('weather')
    op.drop_table('person')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.create_table('weather',
    sa.Column('day', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('temp', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('condition', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('aggregator')
    # ### end Alembic commands ###
